# ------------------------
# 🗄️ Neo4j AuraDB
# ------------------------
NEO4J_URI = "neo4j+s://<your-database-id>.databases.neo4j.io"
NEO4J_USER = "neo4j"
NEO4J_PASSWORD = "<your-neo4j-password>"
NEO4J_DATABASE = "neo4j"  # default db name, change if you use another name